source 'https://github.com/CocoaPods/Specs.git'
xcodeproj 'Taggy.xcodeproj/'

platform :ios, "7.0"

target "Taggy" do

pod 'TesseractOCRiOS', :head
pod 'GPUImage', '~> 0.1.6'
pod 'InAppSettingsKit', '~> 2.3'
pod 'Realm', '~> 0.88'
pod 'SVProgressHUD', :head
pod 'Masonry', '~> 0.5.3'
pod 'Reachability'

pod 'FlurrySDK', '~> 5.4.0'
pod 'GoogleAnalytics-iOS-SDK', '~> 3.10'
pod 'YandexMobileMetrica', '~> 1.6.1'

pod 'ARAnalytics/Flurry'
pod 'ARAnalytics/GoogleAnalytics'
pod 'ARAnalytics/YandexMobileMetrica'

end

